version: "3.8"
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1  # Faster startup
    volumes:
      - ~/kavita/config:/config:z
      - /mnt/Watch-Library/Book-Library:/data:ro,z  # Read-only for safety
    ports:
      - 5000:5000
    restart: unless-stopped
    mem_limit: 4g  # Increased for PDF handling
    memswap_limit: 8g  # Allows memory overflow to swap
    cpu_shares: 768  # Higher CPU priority (default=1024, max=1024)
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - kavita_network
    deploy:
      resources:
        limits:
          cpus: "2.0"  # Maximum CPU cores to use
          memory: 4G

networks:
  kavita_network:
    driver: bridge