services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    network_mode: host
    volumes:
      - ./config:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped