version: '3.8'

services:
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: "${PUID}:${PGID}"
    ports:
      - "9999:9999"
    volumes:
      - ${CONFIG_DIR}:/data
      - ${MEDIA_DIR}:/video

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: "${PUID}:${PGID}"
    environment:
      - WORKER_ID=handbrake-worker
      - SERVER_URL=http://handbrake-server
      - SERVER_PORT=9999
    volumes:
      - ${MEDIA_DIR}:/video
    depends_on:
      - handbrake-server
