services:
  handbrake:
    build: .
    container_name: HandbrakeGUI
    ports:
      - "10000:10000"  # Xpra WebSocket
    environment:
      - DISPLAY=:0
      - XDG_RUNTIME_DIR=/run/user/1000
    volumes:
      - ${MEDIA_DIR}:/home/appuser/media
    user: "${PUID}:${PGID}"
    restart: unless-stopped
