services:
  handbrake:
    build:
      context: .
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    container_name: HandbrakeGUI
    ports:
      - "9999:10000"
    volumes:
      - "${MEDIA_DIR}:/media"
      - "${CONFIG_DIR}:/config"
    environment:
      - DISPLAY=:0
    restart: unless-stopped