services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-once
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --run-once --label-enable