version: "3.8"

services:
  portainer:
    container_name: portainer-central
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8000:8000"
      - "9443:9443"
    network_mode: bridge

volumes:
  portainer_data:
    driver: local
